// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"OnlineParty","status":false,"description":"","parameters":{}},
{"name":"Community_Basic","status":true,"description":"Basic plugin for manipulating important parameters.","parameters":{"cacheLimit":"20","screenWidth":"816","screenHeight":"624","changeWindowWidthTo":"","changeWindowHeightTo":"","renderingMode":"auto","alwaysDash":"off"}},
{"name":"MadeWithMv","status":false,"description":"Show a Splash Screen \"Made with MV\" and/or a Custom Splash Screen before going to main screen.","parameters":{"Show Made With MV":"true","Made with MV Image":"MadeWithMv","Show Custom Splash":"false","Custom Image":"","Fade Out Time":"120","Fade In Time":"120","Wait Time":"160"}},
{"name":"OnlineCharacterPortal","status":false,"description":"Plugin used with Online Core to establish User Login/Registration and Character Creation and Selection","parameters":{}},
{"name":"PlayerCaster","status":false,"description":"","parameters":{}},
{"name":"ActorEnemies","status":true,"description":"v1.2 - Allows you to use side-view actors as enemies.","parameters":{}},
{"name":"OnlineBattle","status":false,"description":"","parameters":{}},
{"name":"OnlineCore","status":false,"description":"Plugin to support online play.","parameters":{}},
{"name":"OnlinePartyPortal","status":false,"description":"","parameters":{}},
{"name":"OnlineSystem","status":true,"description":"","parameters":{}}
];
